name: Generator Auto VPN

on:
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
          - 1secmail
          - guerrillamail
          - developermail
          - mailticking
        default: developermail
      key_type:
        description: 'Choose the key type'
        required: true
        type: choice
        options:
        - --key
        - --small-business-key
        - --vpn-codes
        default: --vpn-codes
  #schedule:
   # - cron: "0 */1 * * *"

jobs:
  GenerateKey:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key
        run: |
          ACCOUNT=0
          KEY=1
          MAIL=developermail
          KEY_TYPE=--vpn-codes

          git clone https://github.com/Shariful797/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip install -r requirements.txt

          if [[ ${KEY} -ne 0 ]]; then
            seq 1 ${KEY} | xargs -I {} -P ${KEY} python3 main.py --chrome --vpn-codes --email-api ${MAIL} --token ${{ secrets.TOKEN }} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          else
              echo "No accounts or keys to generate." >> $GITHUB_STEP_SUMMARY
          fi
